apiVersion: v1
kind: Service
metadata:
  name: k10-frontend
  namespace: kasten-io
  labels:
    app: k10
    component: frontend
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: k10
    component: frontend
  type: ClusterIP 