apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
  namespace: gitea
data:
  app.ini: |
    [server]
    DOMAIN = gitea.gitea.svc.cluster.local
    ROOT_URL = http://gitea.gitea.svc.cluster.local/
    HTTP_ADDR = 0.0.0.0
    HTTP_PORT = 3000
    SSH_DOMAIN = gitea.gitea.svc.cluster.local
    SSH_PORT = 22
    [database]
    DB_TYPE = sqlite3
    PATH = /data/gitea/gitea.db
    [repository]
    ROOT = /data/git/repositories
    [security]
    INSTALL_LOCK = false
    [service]
    DISABLE_REGISTRATION = false
    REQUIRE_SIGNIN_VIEW = false
    [session]
    PROVIDER = memory
    [log]
    MODE = console
    LEVEL = Info 