apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitea
  namespace: gitea
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitea
  namespace: gitea
subjects:
- kind: ServiceAccount
  name: gitea
  namespace: gitea
roleRef:
  kind: Role
  name: gitea
  apiGroup: rbac.authorization.k8s.io 