apiVersion: v1
kind: Service
metadata:
  name: amer-cv-service
spec:
  selector:
    app: cv
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080