apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "2"
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-04-10T12:01:17Z"
  generation: 1
  labels:
    app: amer-project
    pod-template-hash: 6f7cdd845c
  name: amer-project-6f7cdd845c
  namespace: amer-project
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: amer-project
    uid: edfd14a4-1840-4947-af25-2d17d327af6a
  resourceVersion: "384174"
  uid: 8b4e6340-d4f3-48ab-aab0-ef2c0b745776
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amer-project
      pod-template-hash: 6f7cdd845c
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: amer-project
        pod-template-hash: 6f7cdd845c
    spec:
      containers:
      - image: amer30004ever/proj
        imagePullPolicy: Always
        name: proj
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
