apiVersion: v1
kind: Service
metadata:
  name: amer-project-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: amer-project
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
    protocol: TCP 