apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2025-04-10T12:01:17Z"
    generateName: amer-project-6f7cdd845c-
    labels:
      app: amer-project
      pod-template-hash: 6f7cdd845c
    name: amer-project-6f7cdd845c-gs5d8
    namespace: amer-project
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: amer-project-6f7cdd845c
      uid: 8b4e6340-d4f3-48ab-aab0-ef2c0b745776
    resourceVersion: "722471"
    uid: 345e0451-e8b0-4f75-b700-5183c02643d7
  spec:
    containers:
    - image: amer30004ever/proj
      imagePullPolicy: Always
      name: proj
      ports:
      - containerPort: 80
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-6qb7f
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: worker02
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-6qb7f
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2025-04-24T22:22:34Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2025-04-10T12:01:17Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2025-04-24T22:22:34Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2025-04-24T22:22:34Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2025-04-10T12:01:17Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://eeff70b21271d9a5274d030f0b0b966e3087413c60ace8129888ea34e4a3a771
      image: docker.io/amer30004ever/proj:latest
      imageID: docker.io/amer30004ever/proj@sha256:9e60b8ba42bdcda8a0789a104d0931a386cc1625cac30219299f0c87dabb67a6
      lastState:
        terminated:
          containerID: containerd://a90ef7506c098d65f886a18adcd02b124dcfeb770181be325eed50036d3760dd
          exitCode: 255
          finishedAt: "2025-04-24T22:08:12Z"
          reason: Unknown
          startedAt: "2025-04-24T21:35:02Z"
      name: proj
      ready: true
      restartCount: 3
      started: true
      state:
        running:
          startedAt: "2025-04-24T22:22:33Z"
    hostIP: 192.168.2.152
    hostIPs:
    - ip: 192.168.2.152
    phase: Running
    podIP: 10.36.0.3
    podIPs:
    - ip: 10.36.0.3
    qosClass: BestEffort
    startTime: "2025-04-10T12:01:17Z"
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"amer-project"},"name":"amer-project","namespace":"amer-project"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"amer-project"}},"strategy":{},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"amer-project"}},"spec":{"containers":[{"image":"amer30004ever/proj","name":"proj","ports":[{"containerPort":80}],"resources":{}}]}}},"status":{}}
    creationTimestamp: "2025-04-10T12:01:17Z"
    generation: 1
    labels:
      app: amer-project
    name: amer-project
    namespace: amer-project
    resourceVersion: "723499"
    uid: edfd14a4-1840-4947-af25-2d17d327af6a
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: amer-project
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: amer-project
      spec:
        containers:
        - image: amer30004ever/proj
          imagePullPolicy: Always
          name: proj
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-04-10T12:01:17Z"
      lastUpdateTime: "2025-04-10T12:01:20Z"
      message: ReplicaSet "amer-project-6f7cdd845c" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2025-04-24T22:34:51Z"
      lastUpdateTime: "2025-04-24T22:34:51Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2025-04-10T12:01:17Z"
    generation: 1
    labels:
      app: amer-project
      pod-template-hash: 6f7cdd845c
    name: amer-project-6f7cdd845c
    namespace: amer-project
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: amer-project
      uid: edfd14a4-1840-4947-af25-2d17d327af6a
    resourceVersion: "723475"
    uid: 8b4e6340-d4f3-48ab-aab0-ef2c0b745776
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: amer-project
        pod-template-hash: 6f7cdd845c
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: amer-project
          pod-template-hash: 6f7cdd845c
      spec:
        containers:
        - image: amer30004ever/proj
          imagePullPolicy: Always
          name: proj
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
kind: List
metadata:
  resourceVersion: ""
