apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2025-04-25T11:38:57Z"
    generateName: gitea-7cc8df858d-
    labels:
      app: gitea
      pod-template-hash: 7cc8df858d
    name: gitea-7cc8df858d-77rhf
    namespace: gitea
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: gitea-7cc8df858d
      uid: c5cbe2d4-18b5-4797-a7bb-b1bb20200d4c
    resourceVersion: "741091"
    uid: 4aea3953-6a85-4f51-9153-3140c0c76633
  spec:
    containers:
    - env:
      - name: GITEA__database__DB_TYPE
        value: sqlite3
      - name: GITEA__database__PATH
        value: /data/gitea/gitea.db
      - name: GITEA__server__DOMAIN
        value: 192.168.2.152
      - name: GITEA__server__ROOT_URL
        value: http://192.168.2.152:30090/
      - name: GITEA__server__HTTP_ADDR
        value: 0.0.0.0
      - name: GITEA__server__HTTP_PORT
        value: "3000"
      - name: GITEA__server__DISABLE_SSH
        value: "false"
      - name: GITEA__server__SSH_PORT
        value: "22"
      - name: GITEA__server__START_SSH_SERVER
        value: "true"
      image: gitea/gitea:1.21.7
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /
          port: 3000
          scheme: HTTP
        initialDelaySeconds: 60
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      name: gitea
      ports:
      - containerPort: 3000
        protocol: TCP
      - containerPort: 22
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /
          port: 3000
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /data
        name: gitea-data
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-zs5rm
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: master-node
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: gitea-data
      persistentVolumeClaim:
        claimName: gitea-data
    - name: kube-api-access-zs5rm
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2025-04-25T11:39:13Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2025-04-25T11:38:58Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2025-04-25T11:39:50Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2025-04-25T11:39:50Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2025-04-25T11:38:58Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://c12e45c80094f8b1fe41cce54ffe3dbbc5d2f1b145e58795570909313638c079
      image: docker.io/gitea/gitea:1.21.7
      imageID: docker.io/gitea/gitea@sha256:daeeb33fb2f90d94876597f3b6c73956687c03250d5e5ca71104fc03b9c626b3
      lastState: {}
      name: gitea
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2025-04-25T11:39:12Z"
    hostIP: 192.168.2.150
    hostIPs:
    - ip: 192.168.2.150
    phase: Running
    podIP: 10.32.0.8
    podIPs:
    - ip: 10.32.0.8
    qosClass: Burstable
    startTime: "2025-04-25T11:38:58Z"
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"gitea"},"name":"gitea","namespace":"gitea"},"spec":{"ports":[{"name":"http","nodePort":30090,"port":3000,"protocol":"TCP","targetPort":3000},{"name":"ssh","nodePort":30022,"port":22,"protocol":"TCP","targetPort":22}],"selector":{"app":"gitea"},"type":"NodePort"}}
    creationTimestamp: "2025-04-24T15:33:44Z"
    labels:
      app: gitea
    name: gitea
    namespace: gitea
    resourceVersion: "705632"
    uid: de0f9051-657a-45c6-a469-ea912046966a
  spec:
    clusterIP: 10.97.85.208
    clusterIPs:
    - 10.97.85.208
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      nodePort: 30090
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: ssh
      nodePort: 30022
      port: 22
      protocol: TCP
      targetPort: 22
    selector:
      app: gitea
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"gitea"},"name":"gitea","namespace":"gitea"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"gitea"}},"template":{"metadata":{"labels":{"app":"gitea"}},"spec":{"containers":[{"env":[{"name":"GITEA__database__DB_TYPE","value":"sqlite3"},{"name":"GITEA__database__PATH","value":"/data/gitea/gitea.db"},{"name":"GITEA__server__DOMAIN","value":"192.168.2.152"},{"name":"GITEA__server__ROOT_URL","value":"http://192.168.2.152:30090/"},{"name":"GITEA__server__HTTP_ADDR","value":"0.0.0.0"},{"name":"GITEA__server__HTTP_PORT","value":"3000"},{"name":"GITEA__server__DISABLE_SSH","value":"false"},{"name":"GITEA__server__SSH_PORT","value":"22"},{"name":"GITEA__server__START_SSH_SERVER","value":"true"}],"image":"gitea/gitea:1.21.7","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/","port":3000},"initialDelaySeconds":60,"periodSeconds":10,"timeoutSeconds":5},"name":"gitea","ports":[{"containerPort":3000},{"containerPort":22}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/","port":3000},"initialDelaySeconds":30,"periodSeconds":10,"timeoutSeconds":5},"resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"100m","memory":"256Mi"}},"volumeMounts":[{"mountPath":"/data","name":"gitea-data"}]}],"volumes":[{"name":"gitea-data","persistentVolumeClaim":{"claimName":"gitea-data"}}]}}}}
    creationTimestamp: "2025-04-25T11:38:57Z"
    generation: 1
    labels:
      app: gitea
    name: gitea
    namespace: gitea
    resourceVersion: "741095"
    uid: 86e9a957-219e-467a-b931-eb3939241804
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: gitea
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: gitea
      spec:
        containers:
        - env:
          - name: GITEA__database__DB_TYPE
            value: sqlite3
          - name: GITEA__database__PATH
            value: /data/gitea/gitea.db
          - name: GITEA__server__DOMAIN
            value: 192.168.2.152
          - name: GITEA__server__ROOT_URL
            value: http://192.168.2.152:30090/
          - name: GITEA__server__HTTP_ADDR
            value: 0.0.0.0
          - name: GITEA__server__HTTP_PORT
            value: "3000"
          - name: GITEA__server__DISABLE_SSH
            value: "false"
          - name: GITEA__server__SSH_PORT
            value: "22"
          - name: GITEA__server__START_SSH_SERVER
            value: "true"
          image: gitea/gitea:1.21.7
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: gitea
          ports:
          - containerPort: 3000
            protocol: TCP
          - containerPort: 22
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data
            name: gitea-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: gitea-data
          persistentVolumeClaim:
            claimName: gitea-data
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-04-25T11:39:50Z"
      lastUpdateTime: "2025-04-25T11:39:50Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2025-04-25T11:38:57Z"
      lastUpdateTime: "2025-04-25T11:39:50Z"
      message: ReplicaSet "gitea-7cc8df858d" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2025-04-25T11:38:57Z"
    generation: 1
    labels:
      app: gitea
      pod-template-hash: 7cc8df858d
    name: gitea-7cc8df858d
    namespace: gitea
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: gitea
      uid: 86e9a957-219e-467a-b931-eb3939241804
    resourceVersion: "741093"
    uid: c5cbe2d4-18b5-4797-a7bb-b1bb20200d4c
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: gitea
        pod-template-hash: 7cc8df858d
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: gitea
          pod-template-hash: 7cc8df858d
      spec:
        containers:
        - env:
          - name: GITEA__database__DB_TYPE
            value: sqlite3
          - name: GITEA__database__PATH
            value: /data/gitea/gitea.db
          - name: GITEA__server__DOMAIN
            value: 192.168.2.152
          - name: GITEA__server__ROOT_URL
            value: http://192.168.2.152:30090/
          - name: GITEA__server__HTTP_ADDR
            value: 0.0.0.0
          - name: GITEA__server__HTTP_PORT
            value: "3000"
          - name: GITEA__server__DISABLE_SSH
            value: "false"
          - name: GITEA__server__SSH_PORT
            value: "22"
          - name: GITEA__server__START_SSH_SERVER
            value: "true"
          image: gitea/gitea:1.21.7
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: gitea
          ports:
          - containerPort: 3000
            protocol: TCP
          - containerPort: 22
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data
            name: gitea-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: gitea-data
          persistentVolumeClaim:
            claimName: gitea-data
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
kind: List
metadata:
  resourceVersion: ""
