apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2025-04-25T19:59:43Z"
    generateName: jenkins-79445478fd-
    labels:
      app: jenkins-server
      pod-template-hash: 79445478fd
    name: jenkins-79445478fd-4rxjt
    namespace: jenkins
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: jenkins-79445478fd
      uid: 447749cc-555e-40e6-906a-35183232bf4d
    resourceVersion: "767893"
    uid: 85053441-87f1-45e8-9e98-580aabf0a158
  spec:
    containers:
    - image: jenkins/jenkins:lts
      imagePullPolicy: IfNotPresent
      name: jenkins
      ports:
      - containerPort: 8080
        protocol: TCP
      - containerPort: 50000
        protocol: TCP
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 500Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/jenkins_home
        name: jenkins-data
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-cvb7n
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: worker02
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: jenkins-data
      persistentVolumeClaim:
        claimName: jenkins-pv-claim
    - name: kube-api-access-cvb7n
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2025-04-25T19:59:43Z"
      status: "False"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2025-04-25T19:59:43Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2025-04-25T19:59:43Z"
      message: 'containers with unready status: [jenkins]'
      reason: ContainersNotReady
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2025-04-25T19:59:43Z"
      message: 'containers with unready status: [jenkins]'
      reason: ContainersNotReady
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2025-04-25T19:59:43Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - image: jenkins/jenkins:lts
      imageID: ""
      lastState: {}
      name: jenkins
      ready: false
      restartCount: 0
      started: false
      state:
        waiting:
          reason: ContainerCreating
    hostIP: 192.168.2.152
    hostIPs:
    - ip: 192.168.2.152
    phase: Pending
    qosClass: Burstable
    startTime: "2025-04-25T19:59:43Z"
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"jenkins-service","namespace":"jenkins"},"spec":{"ports":[{"nodePort":32000,"port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"jenkins-server"},"type":"NodePort"}}
    creationTimestamp: "2025-01-15T21:41:20Z"
    name: jenkins-service
    namespace: jenkins
    resourceVersion: "56690"
    uid: b997ae70-45ae-42bf-85de-681433786c44
  spec:
    clusterIP: 10.105.244.80
    clusterIPs:
    - 10.105.244.80
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 32000
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: jenkins-server
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"jenkins","namespace":"jenkins"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"jenkins-server"}},"template":{"metadata":{"labels":{"app":"jenkins-server"}},"spec":{"containers":[{"image":"jenkins/jenkins:lts","name":"jenkins","ports":[{"containerPort":8080},{"containerPort":50000}],"resources":{"limits":{"cpu":"1","memory":"2Gi"},"requests":{"cpu":"500m","memory":"500Mi"}},"volumeMounts":[{"mountPath":"/var/jenkins_home","name":"jenkins-data"}]}],"serviceAccountName":"default","volumes":[{"name":"jenkins-data","persistentVolumeClaim":{"claimName":"jenkins-pv-claim"}}]}}}}
    creationTimestamp: "2025-01-15T21:41:20Z"
    generation: 1
    name: jenkins
    namespace: jenkins
    resourceVersion: "767894"
    uid: f4bf8cec-b63f-4b57-8957-0b4566685458
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: jenkins-server
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: jenkins-server
      spec:
        containers:
        - image: jenkins/jenkins:lts
          imagePullPolicy: IfNotPresent
          name: jenkins
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 50000
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: default
        serviceAccountName: default
        terminationGracePeriodSeconds: 30
        volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-pv-claim
  status:
    conditions:
    - lastTransitionTime: "2025-01-15T21:41:20Z"
      lastUpdateTime: "2025-01-15T21:41:21Z"
      message: ReplicaSet "jenkins-79445478fd" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2025-04-25T19:59:07Z"
      lastUpdateTime: "2025-04-25T19:59:07Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    observedGeneration: 1
    replicas: 1
    unavailableReplicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2025-01-15T21:41:20Z"
    generation: 1
    labels:
      app: jenkins-server
      pod-template-hash: 79445478fd
    name: jenkins-79445478fd
    namespace: jenkins
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: jenkins
      uid: f4bf8cec-b63f-4b57-8957-0b4566685458
    resourceVersion: "767891"
    uid: 447749cc-555e-40e6-906a-35183232bf4d
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: jenkins-server
        pod-template-hash: 79445478fd
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: jenkins-server
          pod-template-hash: 79445478fd
      spec:
        containers:
        - image: jenkins/jenkins:lts
          imagePullPolicy: IfNotPresent
          name: jenkins
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 50000
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: default
        serviceAccountName: default
        terminationGracePeriodSeconds: 30
        volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-pv-claim
  status:
    fullyLabeledReplicas: 1
    observedGeneration: 1
    replicas: 1
kind: List
metadata:
  resourceVersion: ""
