apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2025-04-23T14:13:13Z"
    generateName: traefik-854fd48499-
    labels:
      app: traefik
      pod-template-hash: 854fd48499
    name: traefik-854fd48499-wzgc8
    namespace: traefik
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: traefik-854fd48499
      uid: 79ba5a12-a5ac-481f-bc4c-ab93804e45ae
    resourceVersion: "722475"
    uid: 042f3071-da14-4c31-8bc4-39da267faac5
  spec:
    containers:
    - args:
      - --api.insecure=true
      - --api.dashboard=true
      - --accesslog
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.kubernetesingress
      image: traefik:latest
      imagePullPolicy: Always
      name: traefik
      ports:
      - containerPort: 80
        protocol: TCP
      - containerPort: 443
        protocol: TCP
      - containerPort: 8080
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-sj2vm
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: worker02
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-sj2vm
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2025-04-24T22:22:49Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2025-04-23T14:13:13Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2025-04-24T22:22:49Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2025-04-24T22:22:49Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2025-04-23T14:13:13Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://f067b701f15a04ec9dafe3e0d774889a4344215ed8e3defde43065089afc89fc
      image: docker.io/library/traefik:latest
      imageID: docker.io/library/traefik@sha256:83f3c843133530e4aa45e6ddc415488583a8a01c88adc5022d415c6e97ceeaae
      lastState:
        terminated:
          containerID: containerd://ae33dcf1426ac8e45853d18d0047508c0351a0f9020067ee83958f79080dc3fa
          exitCode: 255
          finishedAt: "2025-04-24T22:08:12Z"
          reason: Unknown
          startedAt: "2025-04-24T21:37:54Z"
      name: traefik
      ready: true
      restartCount: 2
      started: true
      state:
        running:
          startedAt: "2025-04-24T22:22:48Z"
    hostIP: 192.168.2.152
    hostIPs:
    - ip: 192.168.2.152
    phase: Running
    podIP: 10.36.0.21
    podIPs:
    - ip: 10.36.0.21
    qosClass: BestEffort
    startTime: "2025-04-23T14:13:13Z"
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"traefik","namespace":"traefik"},"spec":{"ports":[{"name":"web","nodePort":30012,"port":80,"targetPort":80},{"name":"websecure","port":443,"targetPort":443},{"name":"admin","nodePort":30013,"port":8080,"targetPort":8080}],"selector":{"app":"traefik"},"type":"NodePort"}}
    creationTimestamp: "2025-04-23T14:01:39Z"
    name: traefik
    namespace: traefik
    resourceVersion: "629353"
    uid: 3f0f0330-c4de-470f-ae44-e4dd438524d9
  spec:
    clusterIP: 10.106.234.16
    clusterIPs:
    - 10.106.234.16
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: web
      nodePort: 30012
      port: 80
      protocol: TCP
      targetPort: 80
    - name: websecure
      nodePort: 30857
      port: 443
      protocol: TCP
      targetPort: 443
    - name: admin
      nodePort: 30013
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: traefik
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"traefik","namespace":"traefik"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"traefik"}},"template":{"metadata":{"labels":{"app":"traefik"}},"spec":{"containers":[{"args":["--api.insecure=true","--api.dashboard=true","--accesslog","--entrypoints.web.address=:80","--entrypoints.websecure.address=:443","--providers.kubernetesingress"],"image":"traefik:latest","name":"traefik","ports":[{"containerPort":80,"protocol":"TCP"},{"containerPort":443,"protocol":"TCP"},{"containerPort":8080,"protocol":"TCP"}],"resources":{}}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}
    creationTimestamp: "2025-04-23T13:09:59Z"
    generation: 3
    name: traefik
    namespace: traefik
    resourceVersion: "723666"
    uid: 5b3aabf4-4781-4058-b498-4441c7b6e0b8
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: traefik
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: traefik
      spec:
        containers:
        - args:
          - --api.insecure=true
          - --api.dashboard=true
          - --accesslog
          - --entrypoints.web.address=:80
          - --entrypoints.websecure.address=:443
          - --providers.kubernetesingress
          image: traefik:latest
          imagePullPolicy: Always
          name: traefik
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-04-23T13:09:59Z"
      lastUpdateTime: "2025-04-23T14:13:24Z"
      message: ReplicaSet "traefik-854fd48499" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2025-04-24T22:35:15Z"
      lastUpdateTime: "2025-04-24T22:35:15Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 3
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2025-04-23T13:09:59Z"
    generation: 2
    labels:
      app: traefik
      pod-template-hash: 5589fd6cd8
    name: traefik-5589fd6cd8
    namespace: traefik
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: traefik
      uid: 5b3aabf4-4781-4058-b498-4441c7b6e0b8
    resourceVersion: "629206"
    uid: 551f6779-7002-4e42-a79f-fa5d48bf5792
  spec:
    replicas: 0
    selector:
      matchLabels:
        app: traefik
        pod-template-hash: 5589fd6cd8
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: traefik
          pod-template-hash: 5589fd6cd8
      spec:
        containers:
        - args:
          - --api.insecure=true
          - --accesslog
          - --entrypoints.web.address=:80
          - --entrypoints.websecure.address=:443
          - --providers.kubernetesingress
          image: traefik:latest
          imagePullPolicy: Always
          name: traefik
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    observedGeneration: 2
    replicas: 0
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "2"
    creationTimestamp: "2025-04-23T14:13:13Z"
    generation: 1
    labels:
      app: traefik
      pod-template-hash: 854fd48499
    name: traefik-854fd48499
    namespace: traefik
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: traefik
      uid: 5b3aabf4-4781-4058-b498-4441c7b6e0b8
    resourceVersion: "723654"
    uid: 79ba5a12-a5ac-481f-bc4c-ab93804e45ae
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: traefik
        pod-template-hash: 854fd48499
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: traefik
          pod-template-hash: 854fd48499
      spec:
        containers:
        - args:
          - --api.insecure=true
          - --api.dashboard=true
          - --accesslog
          - --entrypoints.web.address=:80
          - --entrypoints.websecure.address=:443
          - --providers.kubernetesingress
          image: traefik:latest
          imagePullPolicy: Always
          name: traefik
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"autoscaling/v2","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"name":"traefik","namespace":"traefik"},"spec":{"maxReplicas":3,"metrics":[{"resource":{"name":"cpu","target":{"averageUtilization":80,"type":"Utilization"}},"type":"Resource"}],"minReplicas":1,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"traefik"}}}
    creationTimestamp: "2025-04-23T14:01:37Z"
    name: traefik
    namespace: traefik
    resourceVersion: "659897"
    uid: decfdd37-bc90-4274-80dc-c8d9e452842a
  spec:
    maxReplicas: 3
    metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: traefik
  status:
    conditions:
    - lastTransitionTime: "2025-04-24T09:44:49Z"
      message: the HPA controller was able to get the target's current scale
      reason: SucceededGetScale
      status: "True"
      type: AbleToScale
    - lastTransitionTime: "2025-04-23T14:01:54Z"
      message: 'the HPA was unable to compute the replica count: failed to get cpu
        utilization: unable to get metrics for resource cpu: unable to fetch metrics
        from resource metrics API: the server could not find the requested resource
        (get pods.metrics.k8s.io)'
      reason: FailedGetResourceMetric
      status: "False"
      type: ScalingActive
    currentMetrics:
    - type: ""
    currentReplicas: 1
    desiredReplicas: 0
kind: List
metadata:
  resourceVersion: ""
