apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"applicationset-controller","app.kubernetes.io/name":"argocd-applicationset-controller","app.kubernetes.io/part-of":"argocd"},"name":"argocd-applicationset-controller","namespace":"argocd"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"argocd-applicationset-controller"},"subjects":[{"kind":"ServiceAccount","name":"argocd-applicationset-controller"}]}
    creationTimestamp: "2025-01-15T17:25:25Z"
    labels:
      app.kubernetes.io/component: applicationset-controller
      app.kubernetes.io/name: argocd-applicationset-controller
      app.kubernetes.io/part-of: argocd
    name: argocd-applicationset-controller
    namespace: argocd
    resourceVersion: "40235"
    uid: ec25cc98-bcd7-406e-b945-b916b972a553
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: argocd-applicationset-controller
  subjects:
  - kind: ServiceAccount
    name: argocd-applicationset-controller
kind: List
metadata:
  resourceVersion: ""
