Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true

### Nginx VM ###
  config.vm.define "openstack" do |openstack|
    openstack.vm.box = "ubuntu/jammy64"
    openstack.vm.hostname = "openstack"
  openstack.vm.network "private_network", ip: "192.168.56.11"
  openstack.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "16384"
	 vb.cpus = 2
   end
# Provision the VM with necessary installations
  config.vm.provision "shell", inline: <<-SHELL
    # Update and install dependencies
    sudo yum update -y
	
    
  SHELL
end

end