apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istio-ingressgateway
  template:
    metadata:
      labels:
        app: istio-ingressgateway
        istio: ingressgateway
    spec:
      containers:
      - name: istio-proxy
        image: istio/proxyv2:1.18.0
        ports:
        - containerPort: 8080
        - containerPort: 8443
        - containerPort: 15021
        - containerPort: 15090
        env:
        - name: ISTIO_META_ROUTER_MODE
          value: "standard"
        - name: ISTIO_META_REQUESTED_NETWORK_VIEW
          value: "network1"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 2000m
            memory: 1024Mi
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 15021
          initialDelaySeconds: 5
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /healthz/ready
            port: 15021
          initialDelaySeconds: 5
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http2
    targetPort: 8080
  - port: 443
    name: https
    targetPort: 8443
  - port: 15021
    name: status-port
    targetPort: 15021
  selector:
    app: istio-ingressgateway
---
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway-nodeport
  namespace: istio-system
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
spec:
  type: NodePort
  ports:
  - port: 80
    name: http2
    targetPort: 8080
    nodePort: 30095
  - port: 443
    name: https
    targetPort: 8443
    nodePort: 30096
  - port: 15021
    name: status-port
    targetPort: 15021
    nodePort: 30097
  selector:
    app: istio-ingressgateway 