apiVersion: apps/v1
kind: Deployment
metadata:
  name: istiod
  namespace: istio-system
  labels:
    app: istiod
    istio: pilot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istiod
  template:
    metadata:
      labels:
        app: istiod
    spec:
      containers:
      - name: discovery
        image: docker.io/istio/pilot:1.20.0
        args:
        - "discovery"
        - "--monitoringAddr=:15014"
        - "--log_output_level=default:info"
        - "--domain"
        - "cluster.local"
        - "--keepaliveMaxServerConnectionAge"
        - "30m"
        ports:
        - containerPort: 15010
        - containerPort: 15012
        - containerPort: 15014
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: istiod
  namespace: istio-system
  labels:
    app: istiod
    istio: pilot
spec:
  ports:
  - port: 15010
    name: grpc-xds
    targetPort: 15010
  - port: 15012
    name: https-dns
    targetPort: 15012
  - port: 15014
    name: http-monitoring
    targetPort: 15014
  selector:
    app: istiod 