apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv
  namespace: gitlab
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  local:
    path: /mnt/data/gitlab  # Adjust the path as needed
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker01  # Ensure this matches the node where the local volume is located

