apiVersion: v1
kind: Service
metadata:
  name: k10-gateway
  namespace: kasten-io
  labels:
    app: k10
    component: gateway
spec:
  ports:
  - port: 443
    targetPort: 8000
    protocol: TCP
    name: https
  selector:
    app: k10
    component: gateway
  type: ClusterIP 