apiVersion: v1
kind: Service
metadata:
  name: k10-controller
  namespace: kasten-io
  labels:
    app: k10
    component: controller
spec:
  ports:
  - port: 443
    targetPort: 8002
    protocol: TCP
    name: https
  selector:
    app: k10
    component: controller
  type: ClusterIP 