apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-pv-volume
  namespace: vaultwarden
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/vaultwarden"
