Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  
### DB vm  ####
  config.vm.define "db01" do |db01|
    db01.vm.box = "eurolinux-vagrant/centos-stream-9"
    db01.vm.box_version = "9.0.43"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.15"
    db01.vm.provider "virtualbox" do |vb|
     vb.memory = "600"
   end
   config.vm.provision "shell", inline: <<-SHELL
	# Switch to root user
	sudo -i
	
	#update package list
	yum update -y
	
	# Update package list and install EPEL release
	echo "Installing EPEL release..."
	yum install epel-release -y

	# Install MariaDB and Git
	echo "Installing MariaDB and Git..."
	yum install git mariadb-server -y

	# Start and enable MariaDB service
	echo "Starting and enabling MariaDB service..."
	systemctl start mariadb
	systemctl enable mariadb

	# Run mysql_secure_installation script automatically
	echo "Securing MariaDB..."
	expect <<EOF
	spawn mysql_secure_installation
	expect "Enter current password for root (enter for none):"
	send "\r"
	expect "Set root password? \[Y/n\]"
	send "y\r"
	expect "New password:"
	send "admin123\r"
	expect "Re-enter new password:"
	send "admin123\r"
	expect "Remove anonymous users? \[Y/n\]"
	send "y\r"
	expect "Disallow root login remotely? \[Y/n\]"
	send "y\r"
	expect "Remove test database and access to it? \[Y/n\]"
	send "y\r"
	expect "Reload privilege tables now? \[Y/n\]"
	send "y\r"
	expect eof
	EOF

	# Configure MariaDB: Create database and user
	echo "Configuring MariaDB database and user..."
	mysql -u root -padmin123 <<MYSQL_SCRIPT
	CREATE DATABASE accounts;
	GRANT ALL PRIVILEGES ON accounts.* TO 'admin'@'%' IDENTIFIED BY 'admin123';
	FLUSH PRIVILEGES;
	MYSQL_SCRIPT

	# Download source code and initialize database
	echo "Cloning source code and initializing database..."
	git clone -b main https://github.com/hkhcoder/vprofile-project.git
	cd vprofile-project
	mysql -u root -padmin123 accounts < src/main/resources/db_backup.sql

	# Restart MariaDB service
	echo "Restarting MariaDB service..."
	systemctl restart mariadb

	# Start and configure the firewall to allow access to MariaDB on port 3306
	echo "Configuring firewall..."
	systemctl start firewalld
	systemctl enable firewalld
	firewall-cmd --zone=public --add-port=3306/tcp --permanent
	firewall-cmd --reload

	echo "MariaDB setup is complete."
	SHELL
  end
  
  end