apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"redis","app.kubernetes.io/name":"argocd-redis","app.kubernetes.io/part-of":"argocd"},"name":"argocd-redis","namespace":"argocd"},"rules":[{"apiGroups":[""],"resourceNames":["argocd-redis"],"resources":["secrets"],"verbs":["get"]},{"apiGroups":[""],"resources":["secrets"],"verbs":["create"]}]}
    creationTimestamp: "2025-01-15T17:25:25Z"
    labels:
      app.kubernetes.io/component: redis
      app.kubernetes.io/name: argocd-redis
      app.kubernetes.io/part-of: argocd
    name: argocd-redis
    namespace: argocd
    resourceVersion: "40232"
    uid: 2285c85c-b209-480f-ba2f-e475261a101d
  rules:
  - apiGroups:
    - ""
    resourceNames:
    - argocd-redis
    resources:
    - secrets
    verbs:
    - get
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - create
kind: List
metadata:
  resourceVersion: ""
