apiVersion: v1
items:
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2025-01-15T00:31:47Z"
    generation: 1
    labels:
      app: grafana
      pod-template-hash: 54dd75db65
    name: grafana-54dd75db65
    namespace: grafana
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: grafana
      uid: 84822dcb-c0a2-40ea-9a50-e9430d6723cc
    resourceVersion: "384266"
    uid: 45d2eadf-8c84-4561-b870-502c41a0ea95
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: grafana
        pod-template-hash: 54dd75db65
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: grafana
          pod-template-hash: 54dd75db65
      spec:
        containers:
        - env:
          - name: GF_SECURITY_ADMIN_USER
            value: admin
          - name: GF_SECURITY_ADMIN_PASSWORD
            value: admin
          image: grafana/grafana:latest
          imagePullPolicy: Always
          name: grafana
          ports:
          - containerPort: 3000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 472
          runAsUser: 472
          seLinuxOptions:
            level: s0:c123,c456
        terminationGracePeriodSeconds: 30
        volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-pv-claim
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
kind: List
metadata:
  resourceVersion: ""
