apiVersion: v1
kind: ConfigMap
metadata:
  name: my-pihole-custom-dnsmasq
  namespace: pihole
  labels:
    app: pihole
data:
  addn-hosts: |
    127.0.0.1 localhost
    127.0.0.1 pi.hole
  02-custom.conf: |
    # Custom DNSMasq configuration
    cache-size=10000
    domain-needed
    bogus-priv
    no-resolv
    no-poll
    server=1.1.1.1
    server=1.0.0.1
    server=8.8.8.8
    server=8.8.4.4
    local-ttl=300
    log-queries
    log-facility=/var/log/pihole.log 