apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-data-pv
  labels:
    app: pihole
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/pihole-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dnsmasq-d-pv
  labels:
    app: pihole
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/dnsmasq-d 