apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-data
  namespace: pihole
  labels:
    app: pihole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  volumeName: pihole-data-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dnsmasq-d
  namespace: pihole
  labels:
    app: pihole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: dnsmasq-d-pv 