apiVersion: apps/v1
kind: Deployment
metadata:
  name: k10-auth
  namespace: kasten-io
  labels:
    app: k10
    component: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k10
      component: auth
  template:
    metadata:
      labels:
        app: k10
        component: auth
    spec:
      containers:
      - name: auth
        image: gcr.io/kasten-images/auth:7.5.2
        ports:
        - containerPort: 8001
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: K10_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K10_AUTH_PORT
          value: "8001"
        - name: K10_AUTH_HOST
          value: "0.0.0.0"
        - name: K10_AUTH_TLS_CERT
          value: "/etc/ssl/certs/tls.crt"
        - name: K10_AUTH_TLS_KEY
          value: "/etc/ssl/private/tls.key"
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/ssl/certs
          readOnly: true
        - name: tls-private
          mountPath: /etc/ssl/private
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: k10-auth-tls
      - name: tls-private
        secret:
          secretName: k10-auth-tls