apiVersion: v1
kind: Service
metadata:
  name: k10-auth
  namespace: kasten-io
  labels:
    app: k10
    component: auth
spec:
  ports:
  - port: 443
    targetPort: 8001
    protocol: TCP
    name: https
  selector:
    app: k10
    component: auth
  type: ClusterIP 