apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"notifications-controller","app.kubernetes.io/name":"argocd-notifications-controller","app.kubernetes.io/part-of":"argocd"},"name":"argocd-notifications-controller","namespace":"argocd"},"rules":[{"apiGroups":["argoproj.io"],"resources":["applications","appprojects"],"verbs":["get","list","watch","update","patch"]},{"apiGroups":[""],"resources":["configmaps","secrets"],"verbs":["list","watch"]},{"apiGroups":[""],"resourceNames":["argocd-notifications-cm"],"resources":["configmaps"],"verbs":["get"]},{"apiGroups":[""],"resourceNames":["argocd-notifications-secret"],"resources":["secrets"],"verbs":["get"]}]}
    creationTimestamp: "2025-01-15T17:25:25Z"
    labels:
      app.kubernetes.io/component: notifications-controller
      app.kubernetes.io/name: argocd-notifications-controller
      app.kubernetes.io/part-of: argocd
    name: argocd-notifications-controller
    namespace: argocd
    resourceVersion: "40231"
    uid: 4c89700b-1516-424b-bcba-cfacd63de22e
  rules:
  - apiGroups:
    - argoproj.io
    resources:
    - applications
    - appprojects
    verbs:
    - get
    - list
    - watch
    - update
    - patch
  - apiGroups:
    - ""
    resources:
    - configmaps
    - secrets
    verbs:
    - list
    - watch
  - apiGroups:
    - ""
    resourceNames:
    - argocd-notifications-cm
    resources:
    - configmaps
    verbs:
    - get
  - apiGroups:
    - ""
    resourceNames:
    - argocd-notifications-secret
    resources:
    - secrets
    verbs:
    - get
kind: List
metadata:
  resourceVersion: ""
