apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"notifications-controller","app.kubernetes.io/name":"argocd-notifications-controller","app.kubernetes.io/part-of":"argocd"},"name":"argocd-notifications-controller","namespace":"argocd"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"argocd-notifications-controller"},"subjects":[{"kind":"ServiceAccount","name":"argocd-notifications-controller"}]}
    creationTimestamp: "2025-01-15T17:25:25Z"
    labels:
      app.kubernetes.io/component: notifications-controller
      app.kubernetes.io/name: argocd-notifications-controller
      app.kubernetes.io/part-of: argocd
    name: argocd-notifications-controller
    namespace: argocd
    resourceVersion: "40237"
    uid: 1df89027-5285-4402-84c0-235e28452993
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: argocd-notifications-controller
  subjects:
  - kind: ServiceAccount
    name: argocd-notifications-controller
kind: List
metadata:
  resourceVersion: ""
