apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-service
  namespace: vaultwarden
spec:
  type: NodePort
  selector:
    app: vaultwarden-server
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32001
    protocol: TCP
