apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik
  namespace: traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: traefik
subjects:
- kind: ServiceAccount
  name: traefik
  namespace: traefik
