apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Dinosaur-Game-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Amer30004ever/DevOps-Study.git
    targetRevision: HEAD
    path: ArgoCD/Dinosaur-Game/k8s

  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
