apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceprofiles.linkerd.io
spec:
  group: linkerd.io
  names:
    kind: ServiceProfile
    listKind: ServiceProfileList
    plural: serviceprofiles
    singular: serviceprofile
  scope: Namespaced
  versions:
  - name: v1alpha2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              routes:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    condition:
                      type: object
                      properties:
                        method:
                          type: string
                        pathRegex:
                          type: string
                    responseClasses:
                      type: array
                      items:
                        type: object
                        properties:
                          condition:
                            type: object
                            properties:
                              status:
                                type: string
                          isFailure:
                            type: boolean
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: traffic-splits.split.smi-spec.io
spec:
  group: split.smi-spec.io
  names:
    kind: TrafficSplit
    listKind: TrafficSplitList
    plural: traffic-splits
    singular: traffic-split
  scope: Namespaced
  versions:
  - name: v1alpha2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              service:
                type: string
              backends:
                type: array
                items:
                  type: object
                  properties:
                    service:
                      type: string
                    weight:
                      type: integer 