apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-controller
  namespace: linkerd
spec:
  replicas: 1
  selector:
    matchLabels:
      linkerd.io/control-plane-component: controller
  template:
    metadata:
      labels:
        linkerd.io/control-plane-component: controller
    spec:
      containers:
      - name: public-api
        image: buoyantio/linkerd-controller:1.7.4
        args:
        - "-addr=:8085"
        - "-controller-namespace=linkerd"
        - "-log-level=info"
        - "-metrics-addr=:9995"
        - "-enable-pprof"
        - "-cluster-domain=cluster.local"
        ports:
        - name: http
          containerPort: 8085
        - name: admin-http
          containerPort: 9995
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi
        securityContext:
          runAsUser: 2103
        env:
        - name: LINKERD2_PROXY_LOG
          value: warn,linkerd=info
        - name: LINKERD2_PROXY_BIND_TIMEOUT
          value: 10s
        - name: LINKERD2_PROXY_CONTROL_URL
          value: tcp://linkerd-destination.linkerd.svc.cluster.local:8086
        - name: LINKERD2_PROXY_METRICS_URL
          value: tcp://linkerd-destination.linkerd.svc.cluster.local:8086
---
apiVersion: v1
kind: Service
metadata:
  name: linkerd-controller-api
  namespace: linkerd
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8085
    targetPort: 8085
  selector:
    linkerd.io/control-plane-component: controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-web
  namespace: linkerd
spec:
  replicas: 1
  selector:
    matchLabels:
      linkerd.io/control-plane-component: web
  template:
    metadata:
      labels:
        linkerd.io/control-plane-component: web
    spec:
      containers:
      - name: web
        image: buoyantio/linkerd-web:1.7.4
        args:
        - "-addr=:8084"
        - "-controller-namespace=linkerd"
        - "-log-level=info"
        - "-metrics-addr=:9994"
        - "-linkerd-metrics-api-addr=linkerd-controller-api.linkerd.svc.cluster.local:8085"
        - "-enable-pprof"
        - "-cluster-domain=cluster.local"
        ports:
        - name: http
          containerPort: 8084
        - name: admin-http
          containerPort: 9994
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi
        securityContext:
          runAsUser: 2103
        env:
        - name: LINKERD2_PROXY_LOG
          value: warn,linkerd=info
        - name: LINKERD2_PROXY_BIND_TIMEOUT
          value: 10s
        - name: LINKERD2_PROXY_CONTROL_URL
          value: tcp://linkerd-destination.linkerd.svc.cluster.local:8086
        - name: LINKERD2_PROXY_METRICS_URL
          value: tcp://linkerd-destination.linkerd.svc.cluster.local:8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-destination
  namespace: linkerd
spec:
  replicas: 1
  selector:
    matchLabels:
      linkerd.io/control-plane-component: destination
  template:
    metadata:
      labels:
        linkerd.io/control-plane-component: destination
    spec:
      containers:
      - name: destination
        image: buoyantio/linkerd-destination:1.7.4
        args:
        - "-addr=:8086"
        - "-controller-namespace=linkerd"
        - "-log-level=info"
        - "-metrics-addr=:9996"
        - "-enable-pprof"
        - "-cluster-domain=cluster.local"
        ports:
        - name: grpc
          containerPort: 8086
        - name: admin-http
          containerPort: 9996
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi
        securityContext:
          runAsUser: 2103
        env:
        - name: LINKERD2_PROXY_LOG
          value: warn,linkerd=info
        - name: LINKERD2_PROXY_BIND_TIMEOUT
          value: 10s
        - name: LINKERD2_PROXY_CONTROL_URL
          value: tcp://linkerd-destination.linkerd.svc.cluster.local:8086
        - name: LINKERD2_PROXY_METRICS_URL
          value: tcp://linkerd-destination.linkerd.svc.cluster.local:8086
---
apiVersion: v1
kind: Service
metadata:
  name: linkerd-destination
  namespace: linkerd
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 8086
    targetPort: 8086
  selector:
    linkerd.io/control-plane-component: destination 