apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: loki
spec:
  selector:
    app: loki
  ports:
  - port: 3100
    targetPort: 3100
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: loki
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: promtail
  namespace: loki
spec:
  selector:
    app: promtail
  ports:
  - port: 9080
    targetPort: 9080 